export const PARSED_QUERY_PARAMS = 'PARSED_QUERY_PARAMS';
export const QUERY_PARAM_PARSER_ERRORS = 'QUERY_PARAM_PARSER_ERRORS';
export const QUERY_PARAM_VALIDATION_ERROR = 'QUERY_PARAM_VALIDATION_ERROR';
